name: check-all-ci-result
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
jobs:
  check-another-ci:
    name: check
    runs-on: ubuntu-20.04
    steps:
      - id: check
        uses: lirlia/check-all-ci-completion-action@29c4626071562fdd54c0957333c2e5c6984ad990
        with:
          loop-count: 2
          timeout-seconds: 30
          sleep-seconds: 1
      - run: |
          echo result: ${{ steps.check.outputs.result }}
          echo status: ${{ steps.check.outputs.status }}
