name: check-all-ci-result
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
jobs:
  check-another-ci:
    name: check
    runs-on: ubuntu-20.04
    steps:
      - uses: lirlia/check-all-ci-completion-action@c30aed31ae1c57147484c5bc658c82180e30c7d0
        with:
          loop-count: 3
          timeout-seconds: 30
          sleep-seconds: 1
