name: check-all-ci-result
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
jobs:
  check-another-ci:
    name: check
    runs-on: ubuntu-20.04
    steps:
      - uses: lirlia/check-all-ci-completion-action@b1273db87d19663a7511d7ac3184868d7810349d
        with:
          loop-count: 3
          timeout-seconds: 30
          sleep-seconds: 1
